---
title: "An치lisis exploratorio de los datos"
author: "Ana Laura Diedrichs & Brenda Canizo"
date: "May 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

```{r}
library(readxl)
library(DataExplorer)
#dataset <- read_excel("data/dataset para an치lisis exploratorio.xlsx")
dataset <- read_excel("../data/Dataset para enfoque 2 y 3.xlsx")
```

```{r}
range01 <- function(x){(x-min(x))/(max(x)-min(x))}

dataset <- data.frame(dataset[,1], apply(dataset[-1],2,range01))
#maxs <- apply(dataset[-1], 2, max)
#mins <- apply(dataset[-1], 2, min)
#dataset <- data.frame(cbind(dataset$Origen, scale(dataset[-1], center = mins, scale = maxs) - mins))
#colnames(dataset)[1] <- "Origen"

# quitamos chile del medio
dataset <- dataset %>% filter(Origen != "CH")
```

## Distribuci칩n de las variables

### Intro al dataset

```{r}
t(introduce(dataset))
```

### Boxplot


```{r }
library(DataExplorer)
plot_boxplot(dataset,by="Origen")

```
### Histograma

```{r}
plot_histogram(dataset)
```

### Densidad estimada

```{r}
plot_density(dataset)
```
## Correlaciones

```{r }
plot_correlation(dataset[-1])
```
```{r}
# correr solo para ver reporte, abre pesta침a en navegador
#create_report(dataset)
```

## QQ plot

```{r}
plot_qq(dataset)
```

## Pairs plot

```{r , echo=FALSE}
library(caret)
featurePlot(x=dataset[,c(2,3,4,5,6)], y=as.factor(dataset$Origen),  "pairs", auto.key=list(columns=2))


```
```{r , echo=FALSE}

featurePlot(x=dataset[,c(7,8,9,10,11)], y=as.factor(dataset$Origen),  "pairs", auto.key=list(columns=2))

```

